# -*- coding: utf-8 -*-
"""2017171_2_B

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tWbGyZ5cE3gLzuHeIaay5CjGCYbz_j2D
"""

import numpy as np
import pandas as pd
import random
import string
from itertools import permutations,combinations
import itertools as itr
import re

Dict={
    'A':['A','a','@'],
    'B':['B','b'],
    'C':['C','c','('],
    'D':['d','D'],
    'E':['3','E','e'],
    'F':['F','f'],
    'G':['G','g','6'],
    'H':['H','h','#'],
    'I':['I','i','!','|'],
    'J':['J','j'],
    'K':['K','k'],
    'L':['L','l'],
    'M':['M','m'],
    'N':['N','n'],
    'O':['0','O','o'],
    'P':['P','p'],
    'Q':['Q','q'],
    'R':['R','r','4'],
    'S':['S','$','s','5','&'],
    'T':['+','T','t'],
    'U':['U','u'],
    'V':['V','v','>','<'],
    'W':['W','w'],
    'X':['+','X','x'],
    'Y':['Y','y
    'Z':['Z','z']
}

def list_to_string(s):
  ans="";
  for item in s:
    ans=ans+item
  return ans

def string_to_passwords(s):
  masterlist=[]
  for char in s:
    current_char=char.upper()
    masterlist.append(Dict[current_char])
  combinations = [p for p in itr.product(*masterlist)]  
  return combinations

'''combo=string_to_passwords('Nishant')
print(combo)'''

def password_validator(s):
  reg = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!#%*?&]{4,25}$"
  comp = re.compile(reg)             
  valid = re.search(comp, s)
  if valid:
    return 1
  else:
    return 0

words= open("words.txt", "r")
wordlist=words.readlines()
def dictionary_attack(n):
  passwords_list=[]
  for a in wordlist:
    if (len(a.strip())==n):
      passphrase=string_to_passwords(a.strip())
      for i in passphrase:
        istring=list_to_string(i)
        if(password_validator(istring)==1):
          passwords_list.append(istring) 
  return passwords_list  
input_length=int(input("Enter the desired length: "))
passwords_list=dictionary_attack(input_length)

#print(passwords_list)

with open('output.txt', 'w') as f:
    for item in passwords_list:
        f.write("%s\n" % item)

